# Generated by Django 4.2.30 on 2026-05-13 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(help_text='FIFA-style short code, e.g. BRA', max_length=8, unique=True)),
                ('group_label', models.CharField(blank=True, help_text='e.g. A, B, or empty for knockout-only', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], default='MF', max_length=2)),
                ('club', models.CharField(blank=True, max_length=160)),
                ('is_injured', models.BooleanField(default=False)),
                ('injury_notes', models.CharField(blank=True, max_length=255)),
                ('cards_suspension_notes', models.CharField(blank=True, max_length=255)),
                ('form_notes', models.CharField(blank=True, help_text='Recent performance / media narrative', max_length=500)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.team')),
            ],
            options={
                'ordering': ['team', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(help_text='e.g. Group A – Matchday 1, Round of 16', max_length=80)),
                ('kickoff', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished')], default='scheduled', max_length=16)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tactical_notes_home', models.TextField(blank=True)),
                ('tactical_notes_away', models.TextField(blank=True)),
                ('external_news_digest', models.TextField(blank=True, help_text='Paste or sync summaries from news sites; fed to the agent as context.')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='matches.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='matches.team')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['kickoff', 'id'],
            },
        ),
    ]
