# Generated by Django 4.2.30 on 2026-05-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='competition_display',
            field=models.CharField(blank=True, help_text='Short label for the fixtures strip (e.g. Premier League, MLS).', max_length=80),
        ),
        migrations.AddField(
            model_name='match',
            name='is_world_cup',
            field=models.BooleanField(db_index=True, default=True, help_text='If true, match appears under the World Cup hub; otherwise under Current competitions.'),
        ),
    ]
