# Generated by Django 4.2.30 on 2026-05-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_competition_display_match_is_world_cup'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='performance_summary',
            field=models.TextField(blank=True, help_text='Short curator summary: minutes, goals/assists trend, NT form — fed to the prediction agent.'),
        ),
        migrations.AddField(
            model_name='player',
            name='recent_club_scores',
            field=models.CharField(blank=True, help_text='Compact recent results you curate (e.g. last 5 club: W W L D W). Not auto-scraped.', max_length=120),
        ),
        migrations.AddField(
            model_name='player',
            name='shirt_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Squad number when known (FIFA / federation list).', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='stats_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Optional structured stats (goals, assists, xG string, apps) for the agent; keep small.'),
        ),
    ]
