# Generated by Django 4.2.30 on 2026-05-14 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_player_performance_summary_player_recent_club_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='lineup_away',
            field=models.JSONField(blank=True, default=list, help_text='Optional XI for the away side (same shape as lineup_home).'),
        ),
        migrations.AddField(
            model_name='match',
            name='lineup_home',
            field=models.JSONField(blank=True, default=list, help_text='Optional XI: list of strings or objects, e.g. ["#9 R. Lewandowski", …]'),
        ),
        migrations.AddField(
            model_name='match',
            name='prematch_brief',
            field=models.TextField(blank=True, help_text='Curated one-screen brief (form, injuries, stakes) shown on the public match page.'),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField(blank=True, help_text='Match minute, if known.', null=True)),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('own_goal', 'Own goal'), ('card_yellow', 'Yellow card'), ('card_red', 'Red card'), ('sub', 'Substitution'), ('penalty', 'Penalty'), ('note', 'Note'), ('other', 'Other')], default='note', max_length=20)),
                ('side', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('headline', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
            ],
            options={
                'ordering': ['minute', 'id'],
            },
        ),
    ]
