# Generated by Django 4.2.30 on 2026-05-14 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_lineups_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('url', models.URLField(blank=True, max_length=600)),
                ('source', models.CharField(default='goal.com', max_length=40)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='KnockoutFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=4)),
                ('source_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_feeds_out', to='matches.match')),
                ('target_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_feeds_in', to='matches.match')),
            ],
        ),
        migrations.AddConstraint(
            model_name='knockoutfeed',
            constraint=models.UniqueConstraint(fields=('target_match', 'target_side'), name='uniq_knockout_feed_target_side'),
        ),
    ]
